### ISSUE TITLE
List all connected components?

### ISSUE THREAD

**Issue by bslavchev** [btrekkie/dynamic-connectivity#1]
Hi, I'm looking into using this library for the treedepth decomposition problem in graph theory. I'm toying with algorithm designs and discovering that determining whether our graph is still connected after removing a vertex is the main bottleneck of the algorithm. Essentially, I need to: 

1. Remove a vertex
2. Determine whether the graph is still connected
3. If not, find all the now-separate connected components (and store them separately)
4. Do 1-3 on each of the connected components

From what I can tell from the example code, the main functionality of this library is to determine whether two **vertices** are connected - is there a function that returns whether the **graph** is connected, or all individual connected components? Can these components be easily stored separately? If not, can this functionality be easily added?

Thank you!

**Comment by btrekkie** [comment]
If I follow what you're saying, then for your use case, you're essentially looking for the following operation: remove a vertex V, and return a list of representative vertices for the resulting connected components (ignoring any connected components containing vertices that weren't initially connected to V). The list would contain exactly one vertex from each of the connected components, selected arbitrarly. (Based on this, you can determine whether the subgraph is still connected by checking whether the number of representatives the operation returns is at most 1.)

I believe the following method would work:

```java
Collection<ConnVertex> removeVertexAndGetComponentReps(ConnGraph graph, ConnVertex vertex) {
    Collection<ConnVertex> representatives = new ArrayList<ConnVertex>();
    for (ConnVertex adjVertex : new ArrayList<ConnVertex>(graph.adjacentVertices(vertex))) {
        graph.removeEdge(vertex, adjVertex);
        if (!graph.connected(vertex, adjVertex)) {
            representatives.add(adjVertex);
        }
    }

    // If the ConnGraph is augmented, then call graph.removeVertexAugmentation(vertex) here

    return representatives;
}
```

Here's my argument for why this works: it is invariant that at the end of each iteration of the for loop, `representatives` contains exactly one representative for every connected component except the component containing `vertex` (again, ignoring vertices that weren't initially connected to `vertex`). This is because whenever we remove an edge, there are two possibilities:

- The connected component containing `vertex` consists of the same set of vertices before and after removing the edge, i.e. there is an alternate path from `vertex` to `adjVertex`, other than the edge that formerly connected them. In this case, we don't alter `representatives`.
- The connected component containing `vertex` is split into exactly two connected components: one containing `vertex` and one containing `adjVertex`. In this case, we designate `adjVertex` as the representative of the component that doesn't contain `vertex`.

So that's my reasoning. Let me know if you find an error in my argument. I haven't actually tested the above code, so it might contain syntax or logic errors. And let me know if this operation wasn't what you were looking for or isn't sufficient for your use case.

**Comment by btrekkie** [comment]
I believe my comment addresses this issue. If not, let me know and I can reopen it.
