### ISSUE TITLE
theory behind?

### ISSUE THREAD

**Issue by mzy2240** [btrekkie/dynamic-connectivity#3]
Just wondering whether there are papers or documentations behind the implementation.

**Comment by btrekkie** [comment]
Yup, this is an implementation of the data structure described in section 2 of "Poly-Logarithmic Deterministic Fully-Dynamic Algorithms for Connectivity, Minimum Spanning Tree, 2-Edge, and Biconnectivity" by Holm, de Lichtenberg, and Thorup (but without the B-tree optimization). The paper is available here: https://dl.acm.org/doi/pdf/10.1145/276698.276715 . Actually, my implementation is more closely based on this video lecture describing that data structure: https://ocw.mit.edu/courses/6-851-advanced-data-structures-spring-2012/resources/session-20-dynamic-graphs-ii/ . However, there are some mistakes in that video, which I detail here: https://github.com/btrekkie/dynamic-connectivity/blob/3eda7a57e835a1f87ecc1f32d4ffee647ec45e09/src/main/java/com/github/btrekkie/connectivity/ConnGraph.java#L48 .

I found this to be a challenging data structure to learn, so don't sweat it if you don't fully understand it after one viewing. I didn't.

As for the particulars of the structures I am using (such as using storing `EulerTourEdge` objects that point to the two nodes before visiting the edge, and having a pointer from each vertex to an arbitrarily selected node that visits the vertex), I worked these out on my own, since they were not spelled out in the video lecture. Hopefully, these details are clear enough from the comments in the source code (at least after staring at it for long enough).
